"""minha primeira migrate

Revision ID: 67951df8a757
Revises: 
Create Date: 2024-07-15 21:22:54.237804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67951df8a757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('assunto', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contato')
    # ### end Alembic commands ###
